In [1]:
import pandas as pd

# data merging

In [2]:
#example1
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'], 'data1':range(7)})

In [3]:
print (df1)

   data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b


In [4]:
df2 = pd.DataFrame({'key':['a','b','d'],'data2':range(3)})

In [5]:
print (df2)

   data2 key
0      0   a
1      1   b
2      2   d


In [6]:
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [8]:
dict_name = {"a": 1,"b":2,"c":3}
Create_pandas = pd.DataFrame({"key":['a','b','c','c','b','b','a'],"Data_key": range(7)})
print (Create_pandas)

   Data_key key
0         0   a
1         1   b
2         2   c
3         3   c
4         4   b
5         5   b
6         6   a


In [10]:
def Create_apply(dict_value):
    for value in dict_value.keys():
        if value == 'a':
            dict_value['a'] = 1
        elif value == "b":
            dict_value['b'] = 2
        else:
            dict_value['c'] = 3
    return dict_value


In [13]:
experiment_dict = {"a":'me', 'b': 'elisha', 'c': 'tofunmi'}

In [14]:
apply(Create_apply, experiment_dict)

NameError: name 'apply' is not defined

In [15]:
mapping_list = ['a','b','c','d','a','c','d','l','a','a','b','b','c','c']

In [17]:
result = map(Create_apply, mapping_list)
print (result)

In [18]:
pd.merge(df1, df2,on = "key")

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [22]:
df3 = pd.DataFrame({"lkey": ['b','b','a','c','a','a','b'], 'data1': range(7)})

In [23]:
df4 = pd.DataFrame({'rkey':['a','b','d'], 'data2': range(3)})

In [25]:
pd.merge(df3, df4, left_on = "lkey", right_on = 'rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [27]:
print (df4)

   data2 rkey
0      0    a
1      1    b
2      2    d


In [28]:
pd.merge(df1,df2,how = 'outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [31]:
print(df1)
print (df2)
pd.merge(df1,df2, on = "key")

   data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b
   data2 key
0      0   a
1      1   b
2      2   d


data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [39]:
Dic_me = {'a':2, "b":5, "c":1,"d":8,'e':3}

In [40]:
print (df1)

   data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b


In [49]:
Dic_frame = pd.DataFrame({"key":['a','b','c'], "value":[1,2,3]})

In [50]:
pd.merge(df1,Dic_frame, on = "key")

data1 key  value
0      0   b      2
1      1   b      2
2      6   b      2
3      2   a      1
4      4   a      1
5      5   a      1
6      3   c      3

In [51]:
import numpy as np

In [52]:
arr = np.arange(12).reshape(3,4)

In [53]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
np.concatenate([arr,arr], axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [55]:
s1 = pd.Series([0,1], index = ['a', 'b'])
s2 = pd.Series([2,3,4], index = ['c','d','e'])
s3 = pd.Series([5,6], index = ['f', 'g'])

In [56]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [57]:
pd.concat([s1,s2,s3], axis = 1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [58]:
s4 = pd.concat([s1*5, s3])

In [59]:
s4

a    0
b    5
f    5
g    6
dtype: int64

In [60]:
s1 * 5

a    0
b    5
dtype: int64

In [61]:
s1

a    0
b    1
dtype: int64

In [62]:
pd.concat([s1,s4], axis = 1)


0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [63]:
pd.concat([s1,s4], axis = 1, join = 'inner')

0  1
a  0  0
b  1  5

In [66]:
solution = pd.concat([s1,s2,s3], axis = 1, keys = ['one', 'two', 'three','four'])
print (solution)

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0


In [70]:
pd.DataFrame(solution.unstack())

0
one   a  0.0
      b  1.0
      c  NaN
      d  NaN
      e  NaN
      f  NaN
      g  NaN
two   a  NaN
      b  NaN
      c  2.0
      d  3.0
      e  4.0
      f  NaN
      g  NaN
three a  NaN
      b  NaN
      c  NaN
      d  NaN
      e  NaN
      f  5.0
      g  6.0

In [71]:
np.arange(3)

array([0, 1, 2])

In [72]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2), index = ['a', 'b','c'], columns = ['one','two'])

In [73]:
print (df1)

   one  two
a    0    1
b    2    3
c    4    5


In [74]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2), columns = ['one','two'])

In [75]:
print (df1)

   one  two
0    0    1
1    2    3
2    4    5


In [76]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2))

In [77]:
print (df1)

   0  1
0  0  1
1  2  3
2  4  5


In [78]:
df2 = pd.DataFrame(5+ np.arange(4).reshape(2,2), index = ['a','c'], columns = ['three','four'])

In [79]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2), index = ['a', 'b','c'], columns = ['one','two'])

In [80]:
df2

three  four
a      5     6
c      7     8

In [83]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [82]:
pd.concat([df1,df2], axis = 1, keys = ['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [84]:
pd.concat([df1,df2], axis = 1, keys = ['level1', 'level2'], names = ['upper', 'lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [85]:
df1 = pd.DataFrame(np.random.randn(3,4), columns = ['a','b','c','d'])

In [86]:
df1

a         b         c         d
0  0.747789 -0.108337 -0.303504 -0.397422
1 -1.466676  1.226257 -0.613623 -0.004880
2 -1.967702  0.085574 -2.033055 -0.345721

In [87]:
np.random.randn(1,2)

array([[ 0.59488546,  0.29917763]])

In [88]:
df2 = pd.DataFrame(np.random.randn(2,3), columns = ['b','d','a'])

In [89]:
df2

b         d         a
0  0.541544 -0.627423  0.443758
1  0.533211 -0.258506 -0.434967

In [90]:
pd.concat([df1,df2], ignore_index = True)

a         b         c         d
0  0.747789 -0.108337 -0.303504 -0.397422
1 -1.466676  1.226257 -0.613623 -0.004880
2 -1.967702  0.085574 -2.033055 -0.345721
3  0.443758  0.541544       NaN -0.627423
4 -0.434967  0.533211       NaN -0.258506

In [97]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 6.7, np.nan], index = ['f','e','d','c','b','a'])

In [98]:
b = pd.Series([np.arange(len(a), dtype = np.float64)], index = ['f','e','d','c','b','a'])

In [102]:
b

f    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
e    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
d    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
c    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
b    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
a    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
dtype: object

In [103]:
b[-1] 

array([ 0.,  1.,  2.,  3.,  4.,  5.])

In [104]:
b[-1] = np.nan

In [105]:
b

f    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
e    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
d    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
c    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
b    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
a                               NaN
dtype: object

In [109]:
np.where(pd.isnull(a), b, a)

array([array([ 0.,  1.,  2.,  3.,  4.,  5.]), 2.5,
       array([ 0.,  1.,  2.,  3.,  4.,  5.]), 3.5, 6.7, nan], dtype=object)

In [110]:
pd.isnull(a)

f     True
e    False
d     True
c    False
b    False
a     True
dtype: bool

In [111]:
help (np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x` and `y` need to have the same
        shape as `condition`.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are 1-D, `wh

In [112]:
b[:-2].combine_first(a[2:])

a                               NaN
b                               6.7
c    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
d    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
e    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
f    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
dtype: object

In [113]:
df4 = pd.DataFrame({'a':[1,np.nan,5,np.nan],'b':[np.nan,2,np.nan,6],'c':range(2,18,4)})

In [114]:
df4

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [116]:
df5 = pd.DataFrame({'a':[5,3,np.nan, 3,7],'b':[np.nan, 3, 4,6,8]})

In [117]:
df4.combine_first(df5)

a    b     c
0  1.0  NaN   2.0
1  3.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [118]:
print (df4)

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14


In [119]:
print (df5)

     a    b
0  5.0  NaN
1  3.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0


In [121]:
help (pd.Series.combine_first)

Help on function combine_first in module pandas.core.series:

combine_first(self, other)
    Combine Series values, choosing the calling Series's values
    first. Result index will be the union of the two indexes
    
    Parameters
    ----------
    other : Series
    
    Returns
    -------
    y : Series



In [123]:
pd.Index(['name','elisha','jesutofunmi'])

Index(['name', 'elisha', 'jesutofunmi'], dtype='object')

In [125]:
data = pd.DataFrame(np.arange(6).reshape(2,3),index = pd.Index(['Ohio','Colorado'], name = 'state'), columns = pd.Index(['one','two','three'], name = 'number'))

In [126]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [130]:
try_data = pd.DataFrame(np.arange(18).reshape((3,6)), index= pd.Index(['first_In','second_in','third_in'], name= "load_index"),columns= pd.Index(['first','second','third','fourth','fifth','sixth'], name= 'column_names'))

In [131]:
print (try_data)

column_names  first  second  third  fourth  fifth  sixth
load_index                                              
first_In          0       1      2       3      4      5
second_in         6       7      8       9     10     11
third_in         12      13     14      15     16     17


In [132]:
result =data.stack()

In [133]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [135]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [136]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [146]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [147]:
s1 = pd.Series([0,1,2,3], index= ['a','b','c','d'])
s2 = pd.Series([4,5,6], index = ['c','d','e'])

In [148]:
data2 = pd.concat([s1,s2], keys= ['one','two'])

In [149]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [150]:
Data_fo= pd.DataFrame(data2)

In [152]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [154]:
type(data2.unstack())

pandas.core.frame.DataFrame

In [155]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [157]:
data2
print (type(data2))

<class 'pandas.core.series.Series'>


In [158]:
data2.isnull()

one  a    False
     b    False
     c    False
     d    False
two  c    False
     d    False
     e    False
dtype: bool

In [160]:
data2.unstack().isnull()

a      b      c      d      e
one  False  False  False  False   True
two   True   True  False  False  False

In [161]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [163]:
data2.unstack().stack(dropna = False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [166]:
data[:10]

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [167]:
data['elisha'] = range(data.shape[0])

In [168]:
data

number    one  two  three  elisha
state                            
Ohio        0    1      2       0
Colorado    3    4      5       1

In [171]:
first_try= pd.Series({'Banks':['Bank A','Bank B', 'Bank C','Bank B','Bank A','Bank A','Bank C'], "Earnings":['wer','try','etyy','etyy','yuu','yuut','rerwe']})

In [172]:
Map_dict = {'Bank A': 1, 'Bank B': 2, 'Bank C':3}

In [174]:
first_try['Sort_bank'] = first_try['Banks'].map(str.lower).map(Map_dict)

AttributeError: 'list' object has no attribute 'map'

In [176]:
end = np.random.randn(20)
print (end)

[-0.44905173  0.58552076 -0.35516146 -1.74035678 -0.69855601  0.25395247
  0.6480531  -0.58232965 -0.95113077  1.05995986 -0.22992242  1.7743274
 -0.13947158 -2.32929709  1.01461622  1.9785991  -0.44315436  0.16460483
 -0.17187824 -0.58560649]


In [184]:
pd.cut(end, 2, precision =2)

[(-2.33, -0.18], (-0.18, 1.98], (-2.33, -0.18], (-2.33, -0.18], (-2.33, -0.18], ..., (-0.18, 1.98], (-2.33, -0.18], (-0.18, 1.98], (-0.18, 1.98], (-2.33, -0.18]]
Length: 20
Categories (2, interval[float64]): [(-2.33, -0.18] < (-0.18, 1.98]]

In [189]:
value = np.random.rand(30)

In [190]:
value

array([ 0.88853574,  0.15651161,  0.15129559,  0.06114298,  0.34617536,
        0.40304142,  0.50722176,  0.09204898,  0.16416434,  0.07581881,
        0.30515594,  0.33044967,  0.59440622,  0.32043436,  0.58870325,
        0.03356135,  0.5468018 ,  0.66462462,  0.6515474 ,  0.82900785,
        0.72613542,  0.99768602,  0.52874771,  0.62763853,  0.57588901,
        0.30242536,  0.13385872,  0.86755151,  0.16917983,  0.24075852])

In [191]:
ages = [20,22,25,27, 21,23,37,31,61,45,41,32]

In [192]:
bins = [18,25,35,60,100]

In [193]:
cats = pd.cut(ages, bins)

In [194]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [195]:
cats.labels

C:\Users\ACER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [201]:
pd.cut(ages, [18,26,36,61,100], right = False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [202]:
group_names = ['youth', 'YoungAdult','MiddleAged','Senior']

In [203]:
pd.cut(ages, bins, labels = group_names)

[youth, youth, youth, YoungAdult, youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [MiddleAged < Senior < YoungAdult < youth]

In [204]:
data = np.random.rand(20)

In [205]:
pd.cut(data,4, precision = 2)

[(0.25, 0.49], (0.49, 0.72], (0.72, 0.95], (0.018, 0.25], (0.49, 0.72], ..., (0.018, 0.25], (0.25, 0.49], (0.49, 0.72], (0.49, 0.72], (0.72, 0.95]]
Length: 20
Categories (4, interval[float64]): [(0.018, 0.25] < (0.25, 0.49] < (0.49, 0.72] < (0.72, 0.95]]

In [206]:
pd.cut(data,3, precision = 2)

[(0.33, 0.64], (0.33, 0.64], (0.64, 0.95], (0.018, 0.33], (0.64, 0.95], ..., (0.018, 0.33], (0.33, 0.64], (0.64, 0.95], (0.33, 0.64], (0.64, 0.95]]
Length: 20
Categories (3, interval[float64]): [(0.018, 0.33] < (0.33, 0.64] < (0.64, 0.95]]

In [207]:
pd.cut(data, 2, precision = 2)

[(0.018, 0.49], (0.49, 0.95], (0.49, 0.95], (0.018, 0.49], (0.49, 0.95], ..., (0.018, 0.49], (0.018, 0.49], (0.49, 0.95], (0.49, 0.95], (0.49, 0.95]]
Length: 20
Categories (2, interval[float64]): [(0.018, 0.49] < (0.49, 0.95]]

In [208]:
pd.cut(data,1, precision = 2)

[(0.018, 0.95], (0.018, 0.95], (0.018, 0.95], (0.018, 0.95], (0.018, 0.95], ..., (0.018, 0.95], (0.018, 0.95], (0.018, 0.95], (0.018, 0.95], (0.018, 0.95]]
Length: 20
Categories (1, interval[float64]): [(0.018, 0.95]]

In [209]:
data = np.random.randn(1000)

In [210]:
cats = pd.qcut(data, 4)

In [212]:
print (cats)

[(-0.688, -0.0862], (-0.0862, 0.62], (-2.941, -0.688], (-0.0862, 0.62], (0.62, 3.478], ..., (-0.0862, 0.62], (0.62, 3.478], (-2.941, -0.688], (-0.688, -0.0862], (0.62, 3.478]]
Length: 1000
Categories (4, interval[float64]): [(-2.941, -0.688] < (-0.688, -0.0862] < (-0.0862, 0.62] < (0.62, 3.478]]


In [213]:
pd.value_counts(cats)

(0.62, 3.478]        250
(-0.0862, 0.62]      250
(-0.688, -0.0862]    250
(-2.941, -0.688]     250
dtype: int64

In [214]:
pd.qcut(data, [0,0.1,0.5,0.9,1.0])

[(-1.276, -0.0862], (-0.0862, 1.262], (-2.941, -1.276], (-0.0862, 1.262], (-0.0862, 1.262], ..., (-0.0862, 1.262], (-0.0862, 1.262], (-2.941, -1.276], (-1.276, -0.0862], (1.262, 3.478]]
Length: 1000
Categories (4, interval[float64]): [(-2.941, -1.276] < (-1.276, -0.0862] < (-0.0862, 1.262] < (1.262, 3.478]]

In [215]:
np.random.seed(12345)

In [216]:
print (_)

[(-1.276, -0.0862], (-0.0862, 1.262], (-2.941, -1.276], (-0.0862, 1.262], (-0.0862, 1.262], ..., (-0.0862, 1.262], (-0.0862, 1.262], (-2.941, -1.276], (-1.276, -0.0862], (1.262, 3.478]]
Length: 1000
Categories (4, interval[float64]): [(-2.941, -1.276] < (-1.276, -0.0862] < (-0.0862, 1.262] < (1.262, 3.478]]


In [221]:
data = pd.DataFrame(np.random.randn(1000,4))

In [222]:
print (data)

            0         1         2         3
0    2.916153 -0.686936 -0.840190 -0.961765
1   -0.553477 -0.130925 -0.692635 -0.344306
2   -0.038183 -0.142056  0.235043 -0.542928
3   -1.186480 -0.512167 -0.950216  0.889586
4   -1.583878  0.992379 -2.565816  0.699087
5    0.476634  0.382939  0.271072 -0.464359
6    1.719534 -1.042037 -0.261376  0.809749
7   -0.634174  2.183501 -0.055554 -2.436646
8    0.700068  0.950538  1.258258 -0.241253
9   -0.511061  1.248982 -0.733941  1.162958
10  -0.261632  2.086927  0.177078  0.737390
11  -1.345247  0.585848 -0.693666  0.530821
12  -0.432191 -0.566939 -1.325524 -1.430322
13  -0.670832 -0.887796  0.372837 -0.850192
14  -0.686489  0.207363 -0.266300  0.253912
15  -1.270547  0.682816 -0.648243  0.433294
16   0.157510  1.386222  0.010130  0.457039
17  -0.338315  0.591852  0.502152 -0.798525
18  -0.176708 -0.700087 -0.151055 -0.801394
19   1.180972 -0.624891  0.641305  0.320287
20  -0.819053 -0.203838  1.019282 -0.490059
21  -0.931140 -0.970829 -0.06212

In [223]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.000834     0.008408    -0.034772    -0.013117
std       0.994879     0.996349     0.956520     1.017131
min      -3.530912    -3.024110    -2.657202    -3.105636
25%      -0.706530    -0.661664    -0.693650    -0.691494
50%       0.035344     0.028686     0.013655     0.022859
75%       0.676696     0.671497     0.610255     0.671935
max       3.003284     3.897527     3.160760     3.144389

In [224]:
col = data[3]
print (col)

0     -0.961765
1     -0.344306
2     -0.542928
3      0.889586
4      0.699087
5     -0.464359
6      0.809749
7     -2.436646
8     -0.241253
9      1.162958
10     0.737390
11     0.530821
12    -1.430322
13    -0.850192
14     0.253912
15     0.433294
16     0.457039
17    -0.798525
18    -0.801394
19     0.320287
20    -0.490059
21     0.580561
22     1.028285
23    -0.363162
24    -0.506055
25    -0.681142
26     0.411825
27    -0.480705
28     0.080334
29    -0.884025
         ...   
970   -2.678093
971   -2.683549
972   -1.002259
973    0.243058
974    1.076664
975   -0.445745
976    0.498958
977   -0.442940
978   -0.605688
979    0.152726
980   -0.762278
981   -1.690695
982   -1.057888
983    0.158727
984   -0.083125
985   -0.087651
986    0.892599
987    0.973880
988   -2.131714
989   -2.106138
990   -0.280759
991    1.155407
992    0.462908
993    1.217739
994   -0.505584
995   -0.347142
996    2.893903
997   -0.527738
998    0.659336
999   -0.501171
Name: 3, Length: 1000, d

In [225]:
col[np.abs(col) > 3]

98    -3.105636
537    3.144389
Name: 3, dtype: float64

In [226]:
data[(np.abs(data) >3).any(1)]

0         1         2         3
98   0.813014 -1.202724 -0.286215 -3.105636
110  0.123291 -3.024110 -1.168413 -0.888664
171 -3.530912 -0.576175 -0.750648  0.025443
462 -0.928871  3.061029 -0.297909  0.990886
537  0.836054 -0.780620  0.622791  3.144389
803 -1.554274  3.897527  0.677627 -0.248984
821  0.457118  1.638731  3.160760 -0.718885
831  2.133070  3.048747  0.264626 -0.382165
932  3.003284  2.151570 -0.414736 -0.638405

In [227]:
data[np.abs(data) >3] = np.sign(data) *3

In [228]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.000306     0.007425    -0.034933    -0.013156
std       0.993123     0.992834     0.955996     1.016377
min      -3.000000    -3.000000    -2.657202    -3.000000
25%      -0.706530    -0.661664    -0.693650    -0.691494
50%       0.035344     0.028686     0.013655     0.022859
75%       0.676696     0.671497     0.610255     0.671935
max       3.000000     3.000000     3.000000     3.000000

In [229]:
# permutation and random sampling
df = pd.DataFrame(np.arange(5*4).reshape(5,4))

In [230]:
sampler = np.random.permutation(5)

In [231]:
sampler

array([2, 4, 1, 3, 0])

In [237]:
sampler2 = np.random.permutation(10)
print (sampler2)

[5 2 0 6 4 9 8 1 7 3]


In [241]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3

In [246]:
df.take(np.random.permutation(len(df))[:3])

0  1   2   3
1  4  5   6   7
0  0  1   2   3
2  8  9  10  11

In [247]:
# To generate a sampler with replacement, use np.random.randint
bag = np.array([4,6,-2,5,6])
sampler =np.random.randint(0, len(bag), size = 10)

In [248]:
print (sampler)

[0 1 1 4 2 2 3 0 4 3]


In [249]:
draws = bag.take(sampler)

In [250]:
print (draws)

[ 4  6  6  6 -2 -2  5  4  6  5]


In [251]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'], 'data1':range(6)})

In [268]:
dummies = pd.get_dummies(df['key'], prefix = 'key')

In [269]:
df_with_dummy = df[['data1']].join(dummies)

In [270]:
print (df_with_dummy)

   data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0


   key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0
